VERSION=0.0.1
NOMBRE="TXT_NOMBRE"

N=[0m
G=[01;32m
Y=[01;33m
B=[01;34m

comandos:
	@echo ""
	@echo "${B}Comandos disponibles para ${G}TXT_NOMBRE${N}"
	@echo ""
	@echo "  ${Y}Para desarrolladores${N}"
	@echo ""
	@echo "    ${G}iniciar${N}         Instala dependencias."
	@echo "    ${G}previsualizar${N}   Prueba la aplicacion sobre Huayra."
	@echo ""


iniciar:
	npm install

previsualizar:
	chromium src/index.html
