VERSION=0.0.1
NOMBRE="TXT_NOMBRE"

comandos:
	@echo ""
	@echo "Comandos disponibles:"
	@echo ""
	@echo "  ejecutar_mac    Prueba la aplicacion sobre MacOS"
	@echo ""
	@echo " (los comandos se ejecutan indicando el nombre, por ejemplo 'make ejecutar_linux')"
	@echo ""
	
